[workspace]
members = [
  "radicle",
  "radicle-cob",
  "radicle-cli",
  "radicle-cli-test",
  "radicle-crdt",
  "radicle-crypto",
  "radicle-dag",
  "radicle-httpd",
  "radicle-node",
  "radicle-remote-helper",
  "radicle-ssh",
  "radicle-tools",
  "radicle-tui",
  "radicle-ci",
]
default-members = [
  "radicle",
  "radicle-cli",
  "radicle-cob",
  "radicle-crdt",
  "radicle-crypto",
  "radicle-node",
  "radicle-ssh",
  "radicle-remote-helper",
  "radicle-term",
]

[profile.container]
inherits = "release"
debug = true
incremental = false
