[package]
name = "radicle-remote-helper"
license = "MIT OR Apache-2.0"
version = "0.2.0"
authors = ["Alexis Sellier <alexis@radicle.xyz>"]
edition = "2021"

[dependencies]
thiserror = "1"
radicle-git-ext = { version = "0.6.0" }
localtime = { version = "1.2.0" }

[dependencies.radicle]
path = "../radicle"
version = "0"

[dependencies.radicle-crypto]
path = "../radicle-crypto"
version = "0"

[dependencies.radicle-cli]
path = "../radicle-cli"
version = "0"

[[bin]]
name = "git-remote-rad"
path = "src/git-remote-rad.rs"
