name: Deploy

on:
  push:
    branches:
      - deploy/*

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to the container registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and push radicle-node
        id: radicle-node
        uses: docker/build-push-action@v4
        with:
          context: .
          file: radicle-node/Dockerfile
          push: true
          tags: gcr.io/radicle-services/radicle-node:latest,gcr.io/radicle-services/radicle-node:${{ github.sha }}
          cache-from: type=registry,ref=gcr.io/radicle-services/radicle-node:latest
          cache-to: type=inline
      - name: Build and push radicle-httpd
        id: radicle-httpd
        uses: docker/build-push-action@v4
        with:
          context: .
          file: radicle-httpd/Dockerfile
          push: true
          tags: gcr.io/radicle-services/radicle-httpd:latest,gcr.io/radicle-services/radicle-httpd:${{ github.sha }}
          cache-from: type=registry,ref=gcr.io/radicle-services/radicle-httpd:latest
          cache-to: type=inline
